# generated by datamodel-codegen:
#   filename:  standings.json
#   timestamp: 2022-07-07T15:45:08+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class Standing(BaseModel):
    division_id: int
    division_name: str
    place: int
    flags: str
    team_id: int
    letter: str
    abbreviation: str
    location: str
    nickname: str
    full_name: str
    games_played: int
    wins: int
    losses: int
    ties: int
    points: int
    winning_percentage: int
    points_for: int
    points_against: int
    home_wins: int
    home_losses: int
    home_ties: int
    away_wins: int
    away_losses: int
    away_ties: int
    division_wins: int
    division_losses: int
    division_ties: int
    season: int


class Division(BaseModel):
    division_id: int
    division_name: str
    division_slug: str
    standings: List[Standing]


class Divisions(BaseModel):
    west: Division
    east: Division


class Standings(BaseModel):
    divisions: Divisions
