# generated by datamodel-codegen:
#   filename:  team_leaders_defence_tackles.json
#   timestamp: 2022-07-12T19:38:41+00:00

from __future__ import annotations

from pydantic import BaseModel


class Model(BaseModel):
    season: int
    games_played: int
    tackles_total: int
    tackles_defensive: int
    tackles_specialteams: int
    tackles_for_loss: int
    sacks_qb_made: int
    interceptions_made: int
    interceptions_yards: int
    interceptions_long: int
    interceptions_touchdowns: int
    fumbles_forced: int
    fumble_returns: int
    fumble_returns_yards: int
    fumble_returns_long: int
    fumble_returns_touchdowns: int
    team_abbreviation: str
    team_location: str
    team_nickname: str
