# generated by datamodel-codegen:
#   filename:  team_leaders_game_stats.json
#   timestamp: 2022-07-12T19:27:38+00:00

from __future__ import annotations

from pydantic import BaseModel


class GameStats(BaseModel):
    season: int
    games_played: int
    points: int
    plays: int
    yards: int
    points_pgp: str
    plays_pgp: str
    yards_pgp: str
    yards_per_plays: str
    first_downs: int
    first_downs_pgp: str
    second_downs: int
    second_downs_converted: int
    third_downs: int
    third_downs_converted: int
    team_abbreviation: str
    team_location: str
    team_nickname: str


class Passing(BaseModel):
    season: int
    games_played: int
    points: int
    points_pgp: str
    attempts: int
    completions: int
    completion_pct: str
    attempts_pgp: str
    yards: int
    yards_average: str
    yards_pgp: str
    touchdowns: int
    interceptions: int
    first_downs_passing: int
    first_downs_pct: str
    long: int
    sacks: int
    team_abbreviation: str
    team_location: str
    team_nickname: str


class Rushing(BaseModel):
    season: int
    games_played: int
    points: int
    points_pgp: str
    attempts: int
    attempts_pgp: str
    yards: int
    yards_average: str
    yards_pgp: str
    touchdowns: int
    long: int
    first_downs_rushing: int
    first_downs_pct: str
    rush_min_10: int
    rush_min_20: int
    team_abbreviation: str
    team_location: str
    team_nickname: str


class Receiving(BaseModel):
    season: int
    games_played: int
    points: int
    points_pgp: str
    receptions: int
    yards: int
    yards_after_catch: int
    yards_average: str
    yards_pgp: str
    long: int
    touchdowns: int
    receive_min_30: int
    first_downs_receiving: int
    first_downs_pct: str
    fumbles: int
    team_abbreviation: str
    team_location: str
    team_nickname: str


class Kicking(BaseModel):
    season: int
    games_played: int
    kickoffs: int
    yards: int
    kicks_average: str
    kick_returns: int
    kick_return_average: str
    return_touchdowns: int
    onside_kicks: int
    team_abbreviation: str
    team_location: str
    team_nickname: str


class FieldGoalsConverts(BaseModel):
    season: int
    games_played: int
    attempts: int
    made: int
    field_goals_pct: str
    long: int
    singles: int
    made_01_19: int
    made_20_29: int
    made_30_39: int
    made_40_49: int
    made_50_plus: int
    c1_attempts: int
    c1_made: int
    team_abbreviation: str
    team_location: str
    team_nickname: str


class PuntingKickoffs(BaseModel):
    season: int
    games_played: int
    punts: int
    punts_yards: int
    punts_net_yards: int
    punts_average: str
    punts_net_average: str
    punts_long: int
    punts_singles: int
    kickoffs: int
    kickoffs_yards: int
    kickoffs_net_yards: int
    kickoffs_average: str
    kickoffs_net_average: str
    kickoffs_long: int
    kickoffs_singles: int
    team_abbreviation: str
    team_location: str
    team_nickname: str


class PuntKickoffReturns(BaseModel):
    season: int
    games_played: int
    points: int
    points_pgp: str
    punt_returns: int
    pr_yards: int
    pr_average: str
    pr_long: int
    pr_touchdowns: int
    kickoff_returns: int
    kr_yards: int
    kr_average: str
    kr_long: int
    kr_touchdowns: int
    team_abbreviation: str
    team_location: str
    team_nickname: str
