# generated by datamodel-codegen:
#   filename:  player.json
#   timestamp: 2022-06-20T20:51:53+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class School(BaseModel):
    school_id: int
    name: str


class Position(BaseModel):
    position_id: int
    offence_defence_or_special: str
    abbreviation: str
    description: str


class Team(BaseModel):
    is_set: bool
    team_id: int
    location: str
    nickname: str
    abbreviation: str
    season: int
    uniform: int


class PassingItem(BaseModel):
    season: int
    team_abbreviation: str
    games_played: int
    pass_attempts: int
    pass_completions: int
    pass_percentage: str
    pass_net_yards: int
    pass_long: int
    pass_touchdowns: int
    pass_touchdowns_long: int
    pass_interceptions: int
    pass_fumbles: int
    pass_efficiency: str
    pass_interceptions_percentage: str


class RushingItem(BaseModel):
    season: int
    team_abbreviation: str
    games_played: int
    rush_attempts: int
    rush_yards: int
    rush_average: str
    rush_long: int
    rush_touchdowns: int
    rush_touchdowns_long: int
    rush_min_10: int
    rush_min_20: int


class Seasons(BaseModel):
    passing: List[PassingItem]
    rushing: List[RushingItem]


class PassingItem1(BaseModel):
    game_id: int
    game_date: str
    week: int
    season: int
    opponent_team_abbreviation: str
    pass_attempts: int
    pass_completions: int
    pass_percentage: str
    pass_net_yards: int
    pass_long: int
    pass_touchdowns: int
    pass_touchdowns_long: int
    pass_interceptions: int
    pass_fumbles: int
    pass_efficiency: str
    pass_interceptions_percentage: str


class RushingItem1(BaseModel):
    game_id: int
    game_date: str
    week: int
    season: int
    opponent_team_abbreviation: str
    rush_attempts: int
    rush_yards: int
    rush_average: str
    rush_long: int
    rush_touchdowns: int
    rush_touchdowns_long: int
    rush_min_10: int
    rush_min_20: int


class GameByGame(BaseModel):
    passing: List[PassingItem1]
    rushing: List[RushingItem1]


class Player(BaseModel):
    cfl_central_id: int
    stats_inc_id: int
    first_name: str
    middle_name: str
    last_name: str
    birth_date: str
    birth_place: str
    height: str
    weight: int
    rookie_year: int
    foreign_player: bool
    image_url: str
    school: School
    position: Position
    team: Team
    seasons: Seasons
    game_by_game: GameByGame
